version: '3.8'

services:
  mas_api_motorbusiness:
    image: ${DOCKER_REGISTRY-}masinovacoes:latest
    container_name: mas_api_motorbusiness
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgreConnection=Host=postgres;Port=5432;Database=MotorBusiness_Dev;Username=postgres;Password=example

  postgres:
    image: postgres:latest
    container_name: srv-postgres-01
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: MotorBusiness_Dev
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:management
    container_name: srv-rabbitmq-01
    ports:
      - "5672:5672"
      - "15672:15672"
